### ISSUE TITLE
0.7.0.1: “OML Workbench” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml.tycho#14]
The OML WB product for macosx fails to launch.
It did before... Not sure why it's failing now.

**Comment by sjiherzig** [comment]
This is generally a problem with anything downloaded from the internet (not via the app store, etc.), and has been observed to happen with other COTS software we use (e.g., MagicDraw).

Fix for **El Capitan**:
1. Go to "System Preferences"
2. Choose "Security & Privacy"
3. Click the lock at the bottom of the dialog to unlock. You may need to enter your password / a super user password.
4. Select "Anywhere" under "Allow apps download from:"

This option is no longer available / hidden by the gatekeepr on **Sierra**. The following workaround must be applied:
1. Open a new terminal
2. Type the following command: `sudo spctl --master-disable` - you will be prompted for a superuser password
3. Now follow the steps above for El Capitan - the command from step 2 will let the "Anywhere" reappear.

**Comment by castillr** [comment]
I concur with @sjiherzig, the product opened fine on my computer since I had already disabled gatekeeper.

**Comment by NicolasRouquette** [comment]
I am running macOS Sierra; the only options for "Allow apps downloaded from" are:
- App Store
- App Store and identified developers (checked)

There is no third option.
Also, this part can't be edited, even after unlocking the panel.
I think JPL OCIO has restricted access to this system setting for JPL deployments of macosSierra

Bottom line: we should add "identified developers" to the OML WB product.

**Comment by castillr** [comment]
This is something we may want to do in the future but if we actually need to become identified developers for Apple by joining Apple's Developer Program. For now use the second process Sebastian described above.

**Comment by NicolasRouquette** [comment]
Ah, thanks, I managed to replicate the error:

```
java.lang.IllegalArgumentException: There should be exactly 1 Bundle in org.eclipse.xtext.linking.lazy.LazyLinkingResource@2a797a3b uri='platform:/resource/test2/models/www.w3.org/v2001/xsd.oml'
	at gov.nasa.jpl.imce.oml.dsl.generator.OMLGenerator.beforeGenerate(OMLGenerator.java:1661)
	at org.eclipse.xtext.generator.GeneratorDelegate.beforeGenerate(GeneratorDelegate.java:52)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:33)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:564)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:549)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:534)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:280)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:238)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This stack trace clearly shows that the Xtext builder invokes the OML Generator.
This shouldn't happen; the OML Generator is intended to be ran manually and only on an OML Bundle. It is intended to report an error if invoked on an *.oml file that doesn't specify a single bundle. 

The problem comes from this commit: https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml.tycho/commit/ef70de8d9d591821bd1d0efc51375f35128ddbfe?diff=unified

In the oml.dsl.ui `plugin.xml`, the OML Generator was disabled per this article:
https://christiandietrich.wordpress.com/2011/10/15/xtext-calling-the-generator-from-a-context-menu/

The commit re-enabled it. This explains why the Xtext builder runs it (see the above stack trace).
When it runs on a non-bundle *.oml file, it is designed to report an error.
