### ISSUE TITLE
Problems using OML libraries from a command line application.

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml.tycho#15]
The [OML Converter loads *.oml files](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml.converters/blob/master/src/main/scala/gov/nasa/jpl/imce/oml/converters/OMLConverterFromTextualConcreteSyntax.scala#L46) using an `XtextResourceSet`.
This has worked before...

But now, I get a `java.lang.UnsupportedOperationException`:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.eclipse.emf.ecore.impl.MinimalEStoreEObjectImpl.eBasicAdapterListeners(MinimalEStoreEObjectImpl.java:311)
	  at org.eclipse.emf.internal.cdo.CDOObjectImpl.eBasicAdapterListeners(CDOObjectImpl.java:1087)
	  at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.addListener(MinimalEObjectImpl.java:537)
	  at org.eclipse.emf.ecore.impl.MinimalEStoreEObjectImpl.eBasicSetAdapterArray(MinimalEStoreEObjectImpl.java:302)
	  at org.eclipse.emf.ecore.impl.MinimalEObjectImpl$1ArrayDelegatingAdapterList.setData(MinimalEObjectImpl.java:483)
	  at org.eclipse.emf.common.util.ArrayDelegatingEList.addUnique(ArrayDelegatingEList.java:388)
	  at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	  at org.eclipse.xtext.nodemodel.impl.NodeModelBuilder.associateWithSemanticElement(NodeModelBuilder.java:106)
	  at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.associateNodeWithAstElement(AbstractInternalAntlrParser.java:267)
	  at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.forceCreateModelElement(AbstractInternalAntlrParser.java:687)
	  at gov.nasa.jpl.imce.oml.dsl.parser.antlr.internal.InternalOMLParser.ruleExtent(InternalOMLParser.java:230)
	  at gov.nasa.jpl.imce.oml.dsl.parser.antlr.internal.InternalOMLParser.entryRuleExtent(InternalOMLParser.java:184)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.parse(AbstractInternalAntlrParser.java:557)
	  at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doParse(AbstractAntlrParser.java:102)
	  at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.parse(AbstractAntlrParser.java:84)
	  at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doParse(AbstractAntlrParser.java:62)
	  at org.eclipse.xtext.parser.AbstractParser.parse(AbstractParser.java:33)
	  at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:176)
	  at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:100)
	  at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	  at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	  at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	  at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	  at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265)
	  at gov.nasa.jpl.imce.oml.converters.utils.OMLResourceSet$$anonfun$loadOMLResource$1.apply(OMLResourceSet.scala:72)
	  at gov.nasa.jpl.imce.oml.converters.utils.OMLResourceSet$$anonfun$loadOMLResource$1.apply(OMLResourceSet.scala:72)
	  at gov.nasa.jpl.imce.oml.converters.utils.EMFProblems$$anonfun$nonFatalCatch$2.apply(EMFProblems.scala:83)
	  at gov.nasa.jpl.imce.oml.converters.utils.EMFProblems$$anonfun$nonFatalCatch$2.apply(EMFProblems.scala:83)
	  at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	  at gov.nasa.jpl.imce.oml.converters.utils.EMFProblems$.nonFatalCatch(EMFProblems.scala:83)
	  at gov.nasa.jpl.imce.oml.converters.utils.OMLResourceSet$.loadOMLResource(OMLResourceSet.scala:72)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverterFromTextualConcreteSyntax$$anonfun$1$$anonfun$apply$1.apply(OMLConverterFromTextualConcreteSyntax.scala:46)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverterFromTextualConcreteSyntax$$anonfun$1$$anonfun$apply$1.apply(OMLConverterFromTextualConcreteSyntax.scala:45)
	  at scalaz.$bslash$div.flatMap(Either.scala:135)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverterFromTextualConcreteSyntax$$anonfun$1.apply(OMLConverterFromTextualConcreteSyntax.scala:45)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverterFromTextualConcreteSyntax$$anonfun$1.apply(OMLConverterFromTextualConcreteSyntax.scala:43)
	  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	  at scala.collection.immutable.List.foldLeft(List.scala:84)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverterFromTextualConcreteSyntax$.convert(OMLConverterFromTextualConcreteSyntax.scala:43)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverter$.main(OMLConverter.scala:61)
	  at gov.nasa.jpl.imce.oml.converters.OMLConverter.main(OMLConverter.scala:-1)
```

It seems that the Xtext parser makes extensive use of `EAnnotations`; which in turn seems to require that the underlying `ecore` metamodel be implemented *without* the `MinimalEObject` implementation since it clearly does not support annotations.

**Comment by NicolasRouquette** [comment]
The [oml platform feature](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml.tycho/blob/0.7.0.2/features/core/gov.nasa.jpl.imce.oml.platform.feature/feature.xml) is intended to be an aggregate to ensure consistent dependencies for OML-related development across diverse JVM-based ecosystems including Eclipse, Scala, etc...

This feature includes [org.eclipse.emf.cdo](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml.tycho/blob/0.7.0.2/features/core/gov.nasa.jpl.imce.oml.platform.feature/feature.xml#L77) feature, which as of version `4.5.0.v20160607-1254`  includes the following plugins:

```
   <plugin
         id="org.eclipse.emf.cdo"
         download-size="0"
         install-size="0"
         version="4.5.0.v20160607-1254"
         unpack="false"/>

   <plugin
         id="org.eclipse.emf.cdo.ecore.retrofit"
         download-size="0"
         install-size="0"
         version="4.2.300.v20160301-1326"
         fragment="true"
         unpack="false"/>
```

Outside of Eclipse, adding all the plugin jars from the oml platform feature results in a conflict between the two above plugins since they both provide `org.eclipse.emf.cdo`-related classes.
When loading an Xtext-based resource, the classloader will load one or the other.
- If it loads `org.eclipse.emf.cdo.ecore.retrofit` then parsing will fail with the above exception.
- If it loads `org.eclipse.emf.cdo`, then parsing will not trigger the the above exception.

**Comment by NicolasRouquette** [comment]
For the time being, the workaround is to delete the `org.eclipse.emf.cdo.ecore.retrofit` jar when extracting the oml platform feature for executing OML-based applications outside of Eclipse.

**Comment by NicolasRouquette** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=517009
