### ISSUE TITLE
Mysterious tycho failure for the OML product

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml.tycho#2]
Configured Travis-CI to build using the official docker image for Maven 3.5 + JDK8.

This builds just like in my development environment, including a mysterious error:
https://travis-ci.org/JPL-IMCE/gov.nasa.jpl.imce.oml.tycho/builds/232629313#L3291

```shell
[INFO] Reactor Summary:
[INFO] 
[INFO] gov.nasa.jpl.imce.oml.root ......................... SUCCESS [  0.310 s]
[INFO] gov.nasa.jpl.imce.oml.plugins ...................... SUCCESS [  0.002 s]
[INFO] gov.nasa.jpl.imce.oml.plugins.core ................. SUCCESS [  0.007 s]
[INFO] gov.nasa.jpl.imce.oml.plugins.runtime .............. SUCCESS [  0.002 s]
[INFO] gov.nasa.jpl.imce.oml.uuid ......................... SUCCESS [  2.998 s]
[INFO] gov.nasa.jpl.imce.oml.model ........................ SUCCESS [  4.752 s]
[INFO] gov.nasa.jpl.imce.oml.runtime ...................... SUCCESS [  0.664 s]
[INFO] gov.nasa.jpl.imce.oml.dsl .......................... SUCCESS [  2.371 s]
[INFO] gov.nasa.jpl.imce.oml.dsl.ide ...................... SUCCESS [  1.212 s]
[INFO] gov.nasa.jpl.imce.oml.dsl.ui ....................... SUCCESS [  0.924 s]
[INFO] gov.nasa.jpl.imce.oml.rcp .......................... SUCCESS [  0.240 s]
[INFO] gov.nasa.jpl.imce.oml.runtime.edit ................. SUCCESS [  0.369 s]
[INFO] gov.nasa.jpl.imce.oml.runtime.ui ................... SUCCESS [  0.575 s]
[INFO] gov.nasa.jpl.imce.oml.features ..................... SUCCESS [  0.002 s]
[INFO] gov.nasa.jpl.imce.oml.features.core ................ SUCCESS [  0.002 s]
[INFO] gov.nasa.jpl.imce.oml.features.runtime ............. SUCCESS [  0.003 s]
[INFO] gov.nasa.jpl.imce.oml.runtime.platform.feature ..... SUCCESS [  1.153 s]
[INFO] gov.nasa.jpl.imce.oml.runtime.feature .............. SUCCESS [  0.263 s]
[INFO] gov.nasa.jpl.imce.oml.core.feature ................. SUCCESS [  0.377 s]
[INFO] gov.nasa.jpl.imce.oml.tests ........................ SUCCESS [  0.002 s]
[INFO] gov.nasa.jpl.imce.oml.tests.core ................... SUCCESS [  0.001 s]
[INFO] gov.nasa.jpl.imce.oml.dsl.tests .................... SUCCESS [  6.141 s]
[INFO] gov.nasa.jpl.imce.oml.releng ....................... SUCCESS [  0.002 s]
[INFO] gov.nasa.jpl.imce.oml.target ....................... SUCCESS [  0.003 s]
[INFO] gov.nasa.jpl.imce.oml.updatesite ................... SUCCESS [ 27.360 s]
[INFO] gov.nasa.jpl.imce.oml.product ...................... FAILURE [ 34.179 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:14 min
[INFO] Finished at: 2017-05-15T23:30:29Z
[INFO] Final Memory: 205M/1071M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:0.26.0:materialize-products (materialize-products) on project gov.nasa.jpl.imce.oml.product: Product with id 'OML Workbench' does not exist in the project -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:0.26.0:materialize-products (materialize-products) on project gov.nasa.jpl.imce.oml.product: Product with id 'OML Workbench' does not exist in the project
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Product with id 'OML Workbench' does not exist in the project
	at org.eclipse.tycho.plugins.p2.director.ProductConfig.checkConfiguredProductsExist(ProductConfig.java:64)
	at org.eclipse.tycho.plugins.p2.director.ProductConfig.<init>(ProductConfig.java:40)
	at org.eclipse.tycho.plugins.p2.director.AbstractProductMojo.getProductConfig(AbstractProductMojo.java:145)
	at org.eclipse.tycho.plugins.p2.director.DirectorMojo.execute(DirectorMojo.java:110)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gov.nasa.jpl.imce.oml.product
```

**Comment by sjiherzig** [comment]
Are you using Maven 3.5 in both cases? Maven can sometimes be a bit tricky to work with in combination with Tycho - typically recommended in such cases (if it isn't a configuration error) is to default to older versions of Maven and Tycho.

**Comment by NicolasRouquette** [comment]
Fixed with Maged's help.
